### ISSUE TITLE
ESPHome 2023.11.6 brakes my panel

### ISSUE THREAD

**Issue by synack666** [Blackymas/NSPanel_HA_Blueprint#1350]
After update ESPHome to 2023.11.6 my panel wont come back.
Still in "initializing..."
Have tried power off/on, and reboot.
During the flashing after update in log was a "exit reparse".
With ESPHome i can see logs wirelessly.

Any idea what could solve this?

**Comment by edwardtfn** [comment]
On the blue boot screen, which versions are shown for TFT, ESPHome and Blueprint?

**Comment by NC1609** [comment]
Good morning same here.
TFT: 4.1.1
ESPHome: nothing
Blueprint: Retry 1...2...3 and so on.

**Comment by synack666** [comment]
only TFT with 4.1, the other wont come

**Comment by Zealand67** [comment]
Same issue here. Update ESPHome to 2023.11.6 break both my NSPanels. Panel show same information as NC1609

**Comment by carter013** [comment]
Hello, same here

**Comment by NC1609** [comment]
Hello,
some additional Information of the Logs:

[E][on_boot:054]: No response from Nextion display

**Comment by randomcoffeesnob** [comment]
Same here.
I think it even started on  2023.11.4
I hoped .6 would fix it, but I am still in the mentioned loop.

**Comment by edwardtfn** [comment]
On your ESPHome yaml, what is the value for `ref: ` under `remote_package`?

**Comment by NC1609** [comment]
> On your ESPHome yaml, what is the value for `ref: ` under `remote_package`?

ref: main

**Comment by synack666** [comment]
[logs_nspanel_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13484750/logs_nspanel_logs.txt)

ref: main

**Comment by randomcoffeesnob** [comment]
[logs_nspanel_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13484757/logs_nspanel_logs.txt)

**Comment by edwardtfn** [comment]
Could you please change to `ref: beta`, install it to your panel (wirelessly is ok), and capture the logs again, please?

**Comment by edwardtfn** [comment]
I've reverted all to v4.1.1, with ESPHome 2023.11.6 and cannot duplicate the issue you are reporting. My panel works just fine. 😞

**Comment by randomcoffeesnob** [comment]
[logs_nspanel_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13484945/logs_nspanel_run.txt)

Nothing changed in my case after switching to beta.

**Comment by edwardtfn** [comment]
Could you please share your ESPHome yaml? Please hide any sensitive info before sharing.

**Comment by NC1609** [comment]
> Could you please share your ESPHome yaml? Please hide any sensitive info before sharing.

substitutions:

###### CHANGE ME START ######

  device_name: "badezimmer_panel" 
  wifi_ssid: "'###"
  wifi_password: "#################"

  nextion_update_url: "http://192.168.178.102:8123/local/nspanel_eu.tft" # URL to local tft File
  #nextion_update_url: "http://192.168.178.102:8123/local/nspanel_blank.tft" # URL to local tft File
  #nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####


##### DO NOT CHANGE ANYTHING! ##### 

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

**Comment by edwardtfn** [comment]
Ok, nothing special... very similar to mine, which is working.

**Comment by synack666** [comment]
[logs_nspanel_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13484999/logs_nspanel_run.txt)

substitutions:

###### CHANGE ME ######

  device_name: "nspanel" 
  wifi_ssid: xxxxxxxx
  wifi_password: xxxxxxxxxxxxxxx

##### CHANGE ME #####



##### DO NOT CHANGE ANYTHING! #####

  nextion_update_url: "http://192.168.0.171:8123/local/nspanel_eu.tft" # URL to local tft File
packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: beta
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

**Comment by edwardtfn** [comment]
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/fd0ec3d5-3281-45bf-a3d4-cb9c6f3f57d1)

I think I could duplicate... Working on it.

**Comment by edwardtfn** [comment]
So, as a temporary solution, changing from `ref: main` to `ref: "v4.1"` worked for me.
I will continue investigating for a more permanent solution.

**Comment by edwardtfn** [comment]
I don't understand... now `ref: main` is working again.

Anyone else tried `ref: "v4.1"` successfully?

**Comment by NC1609** [comment]
> "v4.1"

flashing to v4.1 -> don´t work
flashing to main again -> same result don´t work

**Comment by synack666** [comment]
same as NC1609

**Comment by rjperezcolmenar** [comment]
Same here.
flashing to beta: not working
flashing to v4.1: not working
flashing again to main: not working

**Comment by damminh88** [comment]
same here:
all not working

**Comment by albkk** [comment]
Same here.
I did restore from backup with ESPHome 2023.11.4 and flashed panel with ESPHome 2023.11.4, but still stuck initializing...

**Comment by synack666** [comment]
> Same here. I did restore from backup with ESPHome 2023.11.4 and flashed panel with ESPHome 2023.11.4, but still stuck initializing...

yes, one of my unsuccessful attempts too

**Comment by Cody8Bit** [comment]
Hello, I have the same error, the log shows:
[W][component:214]: Component esphome.coroutine took a long time for an operation (1.53 s).
[W][component:215]: Components should block for at most 20-30ms.
[E][on_boot:054]: No response from Nextion display

**Comment by mariusvaida** [comment]
Same here with the same error in the logs as @Cody8Bit wrote.

**Comment by edwardtfn** [comment]
```log
[W][component:214]: Component esphome.coroutine took a long time for an operation (1.53 s).
[W][component:215]: Components should block for at most 20-30ms.
[E][on_boot:054]: No response from Nextion display
```

This is ESPHome trying to recover from a non-responsive display. It turn off the display for a couple of seconds, then turn on, wait a few more seconds... all the waits are causing this `took a long time for an operation`...

**Comment by lloydbayley** [comment]
Bingo!

**Comment by edwardtfn** [comment]
Ok, now I have to work in a permanent fix for this.
Please keep those lines for now. I will let you know when those are not needed anymore.

**Comment by lloydbayley** [comment]
I've just tested it out on both the US Panel & the EU Panel. All features working and nothing to report.

**Comment by damminh88** [comment]
> Could someone please try adding this to the ESPHome yaml, install it (wireless is ok) and let me know the results (logs, please)?
> 
> ```yaml
> external_components:
>   - source: github://pr#5829
>     components:
>       - nextion
>     refresh: 1s
> ```

it works

**Comment by synack666** [comment]
stupid.... where exact i have to insert?

**Comment by Parateam** [comment]
läuft bei mir auch wieder, danke!

**Comment by synack666** [comment]
> > where exact i have to insert?
> 
> Try like this:
> 
> ```yaml
> substitutions:
> 
> ###### CHANGE ME ######
> 
>   device_name: "nspanel" 
>   wifi_ssid: xxxxxxxx
>   wifi_password: xxxxxxxxxxxxxxx
> 
> ##### CHANGE ME #####
> 
> 
> 
> ##### DO NOT CHANGE ANYTHING! #####
> 
>   nextion_update_url: "http://192.168.0.171:8123/local/nspanel_eu.tft" # URL to local tft File
> packages:
>   ##### download esphome code from Github
>   remote_package:
>     url: https://github.com/Blackymas/NSPanel_HA_Blueprint
>     ref: beta
>     files: [nspanel_esphome.yaml]
>     refresh: 300s
> 
> ##### DO NOT CHANGE ANYTHING! #####
> 
> ##### Temporary code #####
> external_components:
>   - source: github://pr#5829
>     components:
>       - nextion
>     refresh: 1s
> ```

thanks a lot, it works!!

bevore i have had a space in line to much....yaml dont like that *g*, my fault

**Comment by lloydbayley** [comment]
> Danke ! Für die ganzen Infos. Ich habe gleiche Probleme, werde aber nun erst einmal abwarten.

@edwardtfn  arbeitet schnell daran!

**Comment by synack666** [comment]
just my thought, even big established companies don't get that kind of support, thank you very much

**Comment by smarthomefamilyverrips** [comment]
> ```yaml
> ##### Temporary code #####
> external_components:
>   - source: github://pr#5829
>     components:
>       - nextion
>     refresh: 1s
> ```

@edwardtfn do have to use beta version or can let "ref:" on main

**Comment by synack666** [comment]
should i close down here, a solution has been found?

**Comment by smarthomefamilyverrips** [comment]
> ```yaml
> ##### DO NOT CHANGE ANYTHING! #####
> ```

@synack666 maybe you also can answer my question, do I need to use "ref: beta" or can i let it on "ref: main" ?

**Comment by synack666** [comment]
> > ```yaml
> > ##### DO NOT CHANGE ANYTHING! #####
> > ```
> 
> @synack666 maybe you also can answer my question, do I need to use "ref: beta" or can i let it on "ref: main" ?

i have it on "main"

**Comment by smarthomefamilyverrips** [comment]
> > > ```yaml
> > > ##### DO NOT CHANGE ANYTHING! #####
> > > ```
> > 
> > 
> > @synack666 maybe you also can answer my question, do I need to use "ref: beta" or can i let it on "ref: main" ?
> 
> i have it on "main"

Thanks will try it now, hope will work for me also 👍

**Comment by lorddagobert** [comment]
Thank you ... I had the same issue ... now it work fine again

**Comment by Cody8Bit** [comment]
Thank you very much for the quick solution, I had the problem and it has been solved.

**Comment by smarthomefamilyverrips** [comment]
@edwardtfn Works for me also again now, thanks for the quick fix!

**Comment by edwardtfn** [comment]
> @edwardtfn do have to use beta version or can let "ref:" on main

`ref: main`

**Comment by edwardtfn** [comment]
> should i close down here, a solution has been found?

No, please keep this open until we apply the solution to the main code.

**Comment by wobi07** [comment]
I still have problems!
The display remains on Intitialing for me.

**Comment by wobi07** [comment]
Sorry the mistake is mine!
Must have done something wrong.
I just repeated it and now it works for me too!

**Comment by marcinbojko** [comment]
I'd like to confirm, same applied here, extra lines, main branch.

**Comment by drgonz0** [comment]
I need to stop updating in the middle of the night.  This fixed it for me too. 

##### Temporary code #####
external_components:
  - source: github://pr#5829
    components:
      - nextion
    refresh: 1s

**Comment by boctok** [comment]
Just as a curious note, I had the same issue with my NS Panel and noticed after the ESPHome update that it had changed the device name from "nsbath" to "Nsbath", which made me think that caused the issue, since the blueprint was looking specifically for all lower-case letters. I changed it back, but obviously it didn't help. I also noticed that the Automation contained the device name and then everything else was blank and un-editable. i.e. Date format had nothing in the block and there was no way to edit it. Same with everything else below that on the page.

Adding your code fixed it.

My ESPHome page takes forever to load, as well. I see another update to ESPHome coming soon.

**Comment by edwardtfn** [comment]
> I see another update to ESPHome coming soon.

Indeed. I just wanna make sure the fix for this Nextion thing would be included. 😆

**Comment by rasmus-wi** [comment]
Fix worked here too! I reflashed my nspanels with esp-idf framework a while ago, so I thought I'd report that the fix works with that, just in case everyone else were using the arduino framework. :)

**Comment by edwardtfn** [comment]
Anyone available to try `ref: beta`?
If so, please remove the whole part with external_components and reference to PR#5829 (the hot fix from a few hours ago), change to `ref: beta`, clean-up your build files and install it (wirelessly is ok).
Please let me know the results.

**Comment by edwardtfn** [comment]
I can anticipate it will fail with `esp-idf` framework. 😉 
I come back to that later, but I will wanna make sure it work with ESPHome 2023.11.6.

**Comment by pozek** [comment]
> Anyone available to try `ref: beta`? If so, please remove the whole part with external_components and reference to PR#5829 (the hot fix from a few hours ago), change to `ref: beta`, clean-up your build files and install it (wirelessly is ok). Please let me know the results.

everything fine with only  ref: beta

**Comment by lloydbayley** [comment]
> Anyone available to try `ref: beta`? If so, please remove the whole part with external_components and reference to PR#5829 (the hot fix from a few hours ago), change to `ref: beta`, clean-up your build files and install it (wirelessly is ok). Please let me know the results.

Sorry, doing it now...

**Comment by lloydbayley** [comment]
Yep! working here!

**Comment by drgonz0** [comment]
Beta working here now too.  Look good

**Comment by synack666** [comment]
working

**Comment by Lice2** [comment]
Thank you now it works !!!!

**Comment by eavyon** [comment]
Adding that my panel is also working again with the current beta on arduino. No pr.

**Comment by edwardtfn** [comment]
Could you please try again with `beta`.
I've returned with support to `esp-idf`, so it was a significant change (also for the ones with the standard `arduino` framework) and wanna validate it again before releasing.

**Comment by marcinbojko** [comment]
> Could you please try again with `beta`. I've returned with support to `esp-idf`, so it was a significant change (also for the ones with the standard `arduino` framework) and wanna validate it again before releasing.

I have few panels to spare, so I'll try

**Comment by kalagan55** [comment]
> ref: main



> Could someone please try adding this to the ESPHome yaml, install it (wireless is ok) and let me know the results (logs, please)?
> 
> ```yaml
> external_components:
>   - source: github://pr#5829
>     components:
>       - nextion
>     refresh: 1s
> ```

Thanks a lot !
Should we leave it in the configuration for other updates?

**Comment by marcinbojko** [comment]
Works with
```yaml
esp32:
  board: esp32dev
  framework:
    type: esp-idf

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: beta
```

**Comment by TahoeNL** [comment]
Changing ref: to beta fixes my issue, identical to the one reported.

**Comment by edwardtfn** [comment]
> Should we leave it in the configuration for other updates?

I'm finalizing some tests on `beta` and wanna release that very soon (minutes, not days). After that is released, you can remove all this extra code added today. 😉

**Comment by edwardtfn** [comment]
# v4.1.2 - Bug fixes and minor enhancements

Welcome to the v4.1.2 patch!

This update fixes some bugs and enable the use of your panel with ESPHome 2023.11.6.

Below is a detailed list of changes. We recommend reviewing them to understand how this update impacts your setup.

**Compatibility Note:** This patch is fully compatible with components from v4.1 and v4.1.1. Your system will operate seamlessly with a mix of v4.1, v4.1.1 and v4.1.2 components, though we advise updating all components to the latest version for optimal performance.

### Update Instructions
For detailed update procedures, please visit:
- **English guide:** [How To - Update (EN)](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#2-update-blueprint)
- **German guide:** [How To - Update (DE)](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(DE)-HowTo---Alle-wichtigen-Dinge-die-man-wissen-sollte#2-update-blueprint)

## Overview of Changes

| Change | Criticality | Page/Area | Components Affected |
| :-- | :--: | :--: | :--: |
| Fix Nextion not communicating with ESPHome 2023.11.6 | Critical | N/A | ESPHome |
| Fix for icons not updating on Home page | Medium | `home` | Blueprint |
| Fix light icon color not being used for buttons | Minor | `buttonpageXX` | Blueprint |
| Don't show thermostat chip when state is `auto` and no action is available | Minor | `home` | Blueprint |
| Fallback to legacy forecast (attributes based) when new method (service based) fails | Minor | `weatherXX` | Blueprint |
| Fix for button image update when local fallback is enabled | Minor | `home` | ESPHome |
| Add option to wake-up to Climate page | Enhancement | `climate` | ESPHome |
| New switch "Nextion display - Power" which can turn the screen on/off | Enhancement | Diagnostics | ESPHome |

**Comment by TahoeNL** [comment]
Awesome!
Changed ref: back to main, flashed and working like a charm.

Reported versions:
[17:00:15][D][script.check_versions:2146]: ESPHome version: 4.1.2
[17:00:15][D][script.check_versions:2147]: TFT version: 4.1.1
[17:00:15][D][script.check_versions:2149]: Blueprint version: 4.1.1

**Comment by edwardtfn** [comment]
Now you can set it back to `ref: main` and remove the references to external components I've proposed earlier in this thread.

**Comment by edwardtfn** [comment]
Thanks a lot for your support with the tests, logs, feedback...

**Comment by marcinbojko** [comment]
> Thanks a lot for your support with the tests, logs, feedback...

Thank you for being here ;)

**Comment by xagos** [comment]
I have installed the new version 4.1.2 and compiled it with esphome 2023.11.6
I still get this message and the panel can not be addressed by the uart:
[17:46:47][E][on_boot:059]: No response from Nextion display

I have tryed it several times - and I havel cleaned all build files...
Attached you can find my log.
[logs_nspanel4kueche_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13490915/logs_nspanel4kueche_run.txt)

**Comment by Zealand67** [comment]
I can cofirm that re-install ESPHome works with my panel since the 4.1.2 patch. I did not need to chnage anything on my yaml file.

**Comment by eavyon** [comment]
Can confirm that only ref:main without additions now works flawlessly.

**Comment by xagos** [comment]
Thanks for your reply - my changes did not make the thing work ;)
They are needed for my typical setup - and I hope that the encryption and/or the static IP have no influence on the nextion-issue. I just want to point out, that there is a difference to the original file...

[18:06:15][C][wifi_signal.sensor:009]: WiFi Signal 'nspanel4kueche RSSI'
[18:06:15][C][wifi_signal.sensor:009]:   Device Class: 'signal_strength'
[18:06:15][C][wifi_signal.sensor:009]:   State Class: 'measurement'
[18:06:15][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dBm'
[18:06:15][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[18:06:31][D][main:2570]: Exit reparse
[18:06:36][D][sensor:094]: 'nspanel4kueche Uptime seconds': Sending state 30.50200 s with 0 decimals of accuracy
[18:06:48][D][sensor:094]: 'nspanel4kueche RSSI': Sending state -74.00000 dBm with 0 decimals of accuracy
[18:06:51][D][script.nextion_status:2661]: Nextion status:
[18:06:51][D][script.nextion_status:2662]:   Is detected: False
[18:06:51][D][script.nextion_status:2663]:   Is setup:    False
**[18:06:51][E][on_boot:059]: No response from Nextion display**
[18:06:51][D][on_boot:060]: Turn off Nextion
[18:06:51][D][switch:016]: 'nspanel4kueche Nextion display - Power' Turning OFF.
[18:06:51][D][switch:055]: 'nspanel4kueche Nextion display - Power': Sending state OFF
[18:06:51][D][on_boot:046]: Wait 2 seconds
[18:06:53][D][on_boot:063]: Turn on Nextion
[18:06:53][D][switch:012]: 'nspanel4kueche Nextion display - Power' Turning ON.
[18:06:53][D][switch:055]: 'nspanel4kueche Nextion display - Power': Sending state ON
[18:06:53][D][on_boot:046]: Wait 5 seconds
[18:06:58][D][script.nextion_status:2661]: Nextion status:
[18:06:58][D][script.nextion_status:2662]:   Is detected: False
[18:06:58][D][script.nextion_status:2663]:   Is setup:    False
[18:06:58][W][component:214]: Component esphome.coroutine took a long time for an operation (7.03 s).
[18:06:58][W][component:215]: Components should block for at most 20-30ms.
[18:07:02][D][sensor:094]: 'ntc_source': Sending state 1.68300 V with 2 decimals of accuracy
[18:07:02][D][resistance:039]: 'resistance_sensor' - Resistance 11657.1Ω
[18:07:02][D][sensor:094]: 'resistance_sensor': Sending state 11657.14258 Ω with 1 decimals of accuracy
[18:07:02][D][ntc:026]: 'nspanel4kueche Temperature' - Temperature: 21.6°C
[18:07:02][D][sensor:094]: 'nspanel4kueche Temperature': Sending state 21.58875 °C with 1 decimals of accuracy
[18:07:18][D][script.nextion_status:2661]: Nextion status:
[18:07:18][D][script.nextion_status:2662]:   Is detected: False
[18:07:18][D][script.nextion_status:2663]:   Is setup:    False
**[18:07:18][E][on_boot:076]: No response from Nextion display**
[18:07:18][D][on_boot:078]: Finished

**Comment by smarthomefamilyverrips** [comment]
Instal of 4.1.2 with "ref: main" worked for me! Thanks again @edwardtfn !!!

**Comment by xHirscHx** [comment]
Looks good all double check when i get home, Big thxs. now just need to fig out why all my devices in  Alex  app aren't responsive , from same update.

**Comment by CH-Tefi** [comment]
everything looks good, thank you @edwardtfn !!!
