### ISSUE TITLE
Feature request: Traditional chinese support 

### ISSUE THREAD

**Issue by percy10442** [Blackymas/NSPanel_HA_Blueprint#1359]
I am a Taiwanese player. I have used NSPanel_HA_Blueprint and I think it is really great. The only drawback is that it does not support Traditional Chinese and some words will disappear when displayed. I hope it can be supported in the future.

**Comment by edwardtfn** [comment]
The challenge is related to the fonts on the Nextion display. The fonts are the components taking more space on the limited memory, so it's hard to add other charsets.

However, if you wanna play with [Nextion Editor](https://nextion.tech/nextion-editor/), it might be easy for you to just replace the existing fonts (except the ones used for icons) by other fonts with the charset you want.
I know this will be some work from your side, as you have to keep this updated with each version, but as soon you have selected the fonts, it would probably be a couple of minutes to update the TFT files with each version.
I can help you with that if you wanna go this way. 😉

**Comment by bluefoxlee** [comment]
I am actually just doing like @edwardtfn mention. I added 4804 Chinese characters and updated tft for my personal use since Jun, please check [https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/797](url).
Would love to share with files for Taiwanese users or how to do it. 
Not sure where is good place to share. Did post it on Line groups, but it seems no one needs it. ^^

Perhaps fork the project and just update for T.Chinese files?

**Comment by edwardtfn** [comment]
Could you share your font files? On the Nextion Editor you can right click the font and select Export, it will generate a `.zi` file. I can see if that could be added to standard displays (maybe a `nspanel_cn.tft`?)...
No promises... 😉

**Comment by edwardtfn** [comment]
I believe you can attach `.zip` files in a message here.

**Comment by bluefoxlee** [comment]
Will do when I get my laptop at home. but not sure if it's a good idea since it will increase too much of file size / and memories just for one single language? wonder if you do know the file size limit for its tft? or perhaps I can make a huge file test on it (will full CJK perhaps?)

**Comment by sorrypqa** [comment]
Looking forward to it

**Comment by edwardtfn** [comment]
I don't know the limit, but the total memory available in the screen is 16Mb, so we might not be far from a limit already.

**Comment by bluefoxlee** [comment]
@edwardtfn Just update a new 5550 characters font for both Chinese and Japanese. Please find attached 
[5550 Font](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13551148/Chinese.Japanese_5550.zip)

Did add Korean too but can't get Korean work with it though.

![IMG_0404](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/894044/85aa82e6-8a1a-45df-a7ae-62707b2768c6)

**Comment by bluefoxlee** [comment]
Hi @edwardtfn please find attached file for updated [CJK zi Fonts](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13639612/CJK.zip)

It covers:
- 5500 most common use for both Chinese languages.
- Japanese (Need Japanese user for testing)
- Korean (Need Japanese user for testing)

Here is quick demo for display CJK at same time. 

![CJK-Testing](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/894044/aa4b3f3b-4571-479e-b30a-b16c8768ff62)

**Comment by bluefoxlee** [comment]
Thanks @edwardtfn. BTW, What will be the best way to update Zi font (or HMI) next after it release? if need.

**Comment by edwardtfn** [comment]
There's no easy way, but it isn't that hard either.

You need [Nextion Editor](https://nextion.tech/nextion-editor/) which can be used to edit the HMI files available on the repository.
Then you open the file and select the tab "Fonts" on the box at the left bottom:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/20070125-7c8a-4ae8-a60a-fe11cf55c968)

Then find the font you wanna replace, right click and select "Replace", then find the `.zi` file you will use instead.

Note that currently fonts 0 to 6 are for text in different sizes, 7, 8 and 10 are for mdi icons and 9 is used only for the page indicator in the bottom.

After change that, you can go on the top menu and select File > Output to TFT and that will generate a TFT file you can upload to your panel.

**Comment by shing6326** [comment]
thanks @bluefoxlee @edwardtfn for the traditional chinese support. I also added the fonts inside the HMI file, but I also need to double the txt_maxl values in order to display the whole chinese without truncate from the entity page, would it possible to increase the txt_maxl in the v4.2 milestone as well?

**Comment by bluefoxlee** [comment]
> There's no easy way, but it isn't that hard either.

Sorry for the confusion. I actually were asking update zi fonts for the project if 4.2 release. Should I upload here or is there any better way to manage it. perhaps I should upload Chinese/Japanese/Korean character sets text I've been used?

Another issue is word wrapping (line breaking) minor issue, I will open it till after 4.2 released. Holiday is coming. ><

**Comment by bluefoxlee** [comment]
> thanks @bluefoxlee @edwardtfn for the traditional chinese support. I also added the fonts inside the HMI file, but I also need to double the txt_maxl values in order to display the whole chinese without truncate from the entity page, would it possible to increase the txt_maxl in the v4.2 milestone as well?

Wonder if you have any screenshot/photo of the issue? I am thinking if it's word wrapping issue. I will make a test on entity page as well when I get home later. Tks.

**Comment by shing6326** [comment]
![WhatsApp Image 2023-12-15 at 11 35 05_f75d9bf1](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/42719827/5ff922dc-2b21-4a84-8dce-6a97b43b896e)
![WhatsApp Image 2023-12-15 at 11 34 38_8f263f23](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/42719827/5a8e31ce-6e89-4704-8c1d-f612492bf378)

**Comment by shing6326** [comment]
the below one could display the whole text "大埔延長線 非假日" after updated the txt_maxl values

**Comment by edwardtfn** [comment]
> Sorry for the confusion. I actually were asking update zi fonts for the project if 4.2 release. Should I upload here or is there any better way to manage it. perhaps I should upload Chinese/Japanese/Korean character sets text I've been used?

I haven't looked on details at this yet, as I wanna make all the changes to the existing TFTs before creating more variations.
Currently, for the US landscaped version, I just use the EU version and follow [these instructions](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/advanced/hmi/nspanel_us_land_code/instructions.md) to generate the new one, so it takes me no more than a couple of minutes for each release. Ideally we should get to the same level with these new TFTs, and the less the better, so it don't add so much work on each release. All the necessary files (the 2 rotated pics) are already available in the repo.
Another option is to make all the files available (`.zi`) and provide instructions for users to update themselves on each release. This is not my preferred patch.

**Comment by edwardtfn** [comment]
But about how to do this now, let's find a name for this (these?) new TFT(s) and create a folder for those, so you can contribute directly to the repo with PRs.
How are the tests you have done so far? Is it possible to have just one TFT to support all those languages or will we need one set of TFTs per language?

**Comment by edwardtfn** [comment]
And let's talk about file naming. We currently have `nspanel_eu.tft`, `nspanel_us.tft` and `nspanel_us_land.tft`, which refers not to languages, but to the 2 models of panels, with 2 variants for the US model.
How should we name the new files? And do we need the 3 new files from the beginning?
- `nspanel_eu.tft`
- `nspanel_us.tft`
- `nspanel_us_land.tft`
- `nspanel_CJK_eu.tft`
- `nspanel_CJK_us.tft`
- `nspanel_CJK_us_land.tft`

**Comment by edwardtfn** [comment]
By the way, on your files I got fonts size 16, 18, 22 and 26. Don't you think we need sizes 36, 48 and 72 also? I know those are used in very limited places, usually to display numbers, so maybe they are not need, but wanna make sure we are not missing anything.

**Comment by edwardtfn** [comment]
So, I've just pushed to `dev` the first CJK TFT files based on the fonts provided by @bluefoxlee (thanks a lot for that!).

The process looks quite feasible. With the original files, it took me just a couple of minutes to replace the fonts on the 3 files and set the charset variable (which will inform ESPHome that it is a CJK file, just in case) and export to TFT.
The TFTs are obviously bigger than the original ones by almost 50%, but I believe it still feasible. Unless we add too much new features in the future, this should be OK.

As I mentioned before, not all font sizes are available. I also noticed the file names do not match the font size on the file, but I've replaced based on file name anyways.

![Screenshot 2023-12-16 200037](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/8a8f31d4-946c-4843-9b6d-0f0e930aede7)

It's all on `dev` now, and you will find the font files under folder `/dev/ui/fonts/CJK`. Feel free to contribute directly on that folder (always on `dev` branch) and I will be happy to update the TFT files before each release.

And it would be nice if you can test the new files, but that will require ESPHome v2023.12.0 which still on beta and will probably be released this next Wednesday.

**Comment by edwardtfn** [comment]
I will close this for now, just to keep my backlog clearer, but please feel free to continue the discussion here or to reopen if you still finding things that should be changed to be able to consider this as completed. 😉

**Comment by bluefoxlee** [comment]
> the below one could display the whole text "大埔延長線 非假日" after updated the txt_maxl values

@shing6326 I see the issue has been fixed. Thanks edwardtfn for the great project and support.!! 
I wonder if you are from Hong Kong since I see 大埔. I know there are specific characters for HK, and I did not inlclude it. Will that be an issue for HK user? 

>How should we name the new files? And do we need the 3 new files from the beginning?

>How are the tests you have done so far? Is it possible to have just one TFT to support all those languages or will we need one set of TFTs per language?

@edwardtfn Sorry for the later reply. I try not miss any discussion since it's long thread.
yes, I think those 3 name should work. 

I have face any issues so far, either from couple users from China. And yes, one TFT should support all Chinese/Japanese/Korean. however, I don't know any Korean/Japanese user to test it.  Should we move this to discussion section for testing & reporting?

>It's all on dev now, and you will find the font files under folder /dev/ui/fonts/CJK.
>By the way, on your files I got fonts size 16, 18, 22 and 26. Don't you think we need sizes 36, 48 and 72 also?
>As I mentioned before, not all font sizes are available. I also noticed the file names do not match the font size on the file, but I've replaced based on file name anyways.

Will do if I got any font update. I think I will update size 36 later for media player. I try not to re-generate all which will massively increase the font size. I am not quite sure which section use 48/72 and will check it later. or perhaps the better solution will be use smaller/same font on those sections. 

I replace fonttype from Ubuntu to MS YaHei for better result. however, YaHei for some reason is smaller and adding space on top/bottom. So I have to increase 4 level in order to get same results. I am still looking for better solution at moment.

**Comment by edwardtfn** [comment]
> Should we move this to discussion section for testing & reporting?

I think that is a good idea, however I would wait until tomorrow when ESPHome 2023.12.0 (required) is expected to be released, so people will be able to test it.

>  I am not quite sure which section use 48/72 and will check it later. or perhaps the better solution will be use smaller/same font on those sections.

Those fonts are used in just a few places:
- Font 4 (36px):
  - `home.current_temp`
  - `climate.target_temp`
  - `boot.t0` ("Please wait...")
  - `media_player.track`
- Font 5 (48px): `climate.current_temp`
- Font 6 (72px): `home.time`

There is a new functionality coming on v4.2 which allow users to select the font for `home.outdoor_temp` and those sizes are available. We can handle this by just adding a message that those sizes won't be available on CJK fonts.
We can also hard code alternative fonts to specific components when using CJK TFT files... I have to think a bit more in possible side effects, but on my first thoughts it would be visual only.

**Comment by shing6326** [comment]
> > the below one could display the whole text "大埔延長線 非假日" after updated the txt_maxl values
> 
> @shing6326 I see the issue has been fixed. Thanks edwardtfn for the great project and support.!! I wonder if you are from Hong Kong since I see 大埔. I know there are specific characters for HK, and I did not inlclude it. Will that be an issue for HK user?
> 
> > How should we name the new files? And do we need the 3 new files from the beginning?
> 
> > How are the tests you have done so far? Is it possible to have just one TFT to support all those languages or will we need one set of TFTs per language?
> 
> @edwardtfn Sorry for the later reply. I try not miss any discussion since it's long thread. yes, I think those 3 name should work.
> 
> I have face any issues so far, either from couple users from China. And yes, one TFT should support all Chinese/Japanese/Korean. however, I don't know any Korean/Japanese user to test it. Should we move this to discussion section for testing & reporting?
> 
> > It's all on dev now, and you will find the font files under folder /dev/ui/fonts/CJK.
> > By the way, on your files I got fonts size 16, 18, 22 and 26. Don't you think we need sizes 36, 48 and 72 also?
> > As I mentioned before, not all font sizes are available. I also noticed the file names do not match the font size on the file, but I've replaced based on file name anyways.
> 
> Will do if I got any font update. I think I will update size 36 later for media player. I try not to re-generate all which will massively increase the font size. I am not quite sure which section use 48/72 and will check it later. or perhaps the better solution will be use smaller/same font on those sections.
> 
> I replace fonttype from Ubuntu to MS YaHei for better result. however, YaHei for some reason is smaller and adding space on top/bottom. So I have to increase 4 level in order to get same results. I am still looking for better solution at moment.

Hello @bluefoxlee , as I know that the HKSCS extension doesn't consume too much space, it would be perfect for HKers if we include it.

**Comment by bluefoxlee** [comment]
> Hello @bluefoxlee , as I know that the HKSCS extension doesn't consume too much space, it would be perfect for HKers if we include it.

@shing6326 Thank you. I got some information from [here](https://github.com/ichitenfont/suppchara). And according to Wiki, full HKSCS is around 5033 characters. lol let's me see if I can find most common use HKSCS info.

>I think that is a good idea, however I would wait until tomorrow when ESPHome 2023.12.0 (required) is expected to be released, so people will be able to test it.

Roger. Hope won't cause you too much update on this later. 

>By the way, how is time and temperature shown in? Could you please share a picture of your home page?
Maybe those big fonts don't even need a CJK version.

Thanks for the detail info. Will upload Font 4 (36px) later. And should be fine for Font 5/6 for Chinese since we use °, C and F as well. (I believe it's same for Japan and Korea too, unless the project update AM/PM for localization later). 

Please found screenshot for 
Size 72
![72](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/894044/b449dc3e-22b6-4b50-ab4f-79ebd56a5d08)

Size 48
![48](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/894044/a0de8b78-9563-42c6-9ab9-d2e0e1964a9b)

**Comment by edwardtfn** [comment]
> unless the project update AM/PM for localization later

That is using one of the fonts you already sent, so it's just about translations.

Do you wanna provide translations for Chinese so we can try a bit?

**Comment by edwardtfn** [comment]
> BTW, Happy Holiday.

You too!
And thanks a lot for your support here. 🙂

**Comment by edwardtfn** [comment]
> > unless the project update AM/PM for localization later

> That is using one of the fonts you already sent, so it's just about translations.

Code part is done! 😃

**Comment by edwardtfn** [comment]
You need ESPHome v2023.12.0, which is not released yet. 😩

**Comment by edwardtfn** [comment]
Could you please help with the translations for AM and PM?

**Comment by bluefoxlee** [comment]
> You need ESPHome v2023.12.0, which is not released yet. 😩

I am using 2023.12.0b3. 😱
Translation for zh-tw below. will start to use PR then. 

      meridiem:
         am: 上午
         pm: 下午

**Comment by edwardtfn** [comment]
> I am using 2023.12.0b3. 😱

Mmmm. I'm running the same...
When it shows that issue? Could you please share the logs from before those messages?

**Comment by bluefoxlee** [comment]
> Mmmm. I'm running the same... When it shows that issue? Could you please share the logs from before those messages?

Not sure if it's b3 issue, I updated to b4/b5 today and issue has gone.
However it seems 4.2dev.1 of nspanel_us_land and nspanel_CJK_us_land have misplaced.
The button bar shows at bottom. mdi icon is missing Might need more space for meridiem. 

![4 2Dev 1](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/894044/ad228cf0-c861-4f6f-a490-d4c5c1c996e4)

**Comment by edwardtfn** [comment]
Done!

**Comment by edwardtfn** [comment]
[Chinese, Japanese and Korean (CJK) languages - We need help with translations · Blackymas/NSPanel_HA_Blueprint · Discussion #1447 (github.com)](https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1447)

**Comment by bluefoxlee** [comment]
@edwardtfn You are super!. It looks good on T.Chinese.let's see how it goes with Japanese and Korean. 
Meanwhile, I am testing other two font to see if its better and fix pixel high issue. 

For some reason, I can't donate this project from Taiwan. Any other way I can make donation to buy you a coffee and thank you?

**Comment by bluefoxlee** [comment]
Can't really tell the different between two new typefaces, so I have updated/uploaded the original zi font with 48px and raised PR. Tks.

**Comment by percy10442** [comment]
> Hey, I've made quite a lot of changes to `dev` and then updated all the TFT files. If you have a chance, could you please give it a try and let me know if everything still ok?

Hi Edwardtfn , I tried copying npanel_CJK_us_land.tft in the dev folder to home assistant, but there is still a problem with the display. Is there anything I missed?
<img width="1007" alt="截圖 2024-01-02 下午10 22 02" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/78840128/cfe9fd44-0c4e-4241-83b6-f0ae64eabffa">
![IMG_8640](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/78840128/08a85f94-4e6e-42e4-9e50-2d4274fcce4b)
![IMG_8641](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/78840128/e4abf0a8-54b6-4817-b8c1-cbd6c64c8062)
![IMG_8642](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/78840128/b99120f5-c9d6-4b18-8c87-eb19395a3a40)
![IMG_8643](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/78840128/399ae5b1-fdf6-4e80-ab18-0e5d6c3aa149)

**Comment by edwardtfn** [comment]
Could you please share those strings here (as text, not as pictures) so I can try to duplicate this issue?

**Comment by bluefoxlee** [comment]
Kind of wired.. Those are quite common characters. I will make a quick test here as well.

**Comment by edwardtfn** [comment]
> BTW, Perhaps it's better to postpone CJK to 4.3 in order to make more test on it?

I'm thinking about this. I can include all the files on the release, but remove this from the announcements.

**Comment by edwardtfn** [comment]
> Wonder if it's because ESP main branch with Dev tft?

I would expect lots of issues with this combination, but not that one. 😂

**Comment by edwardtfn** [comment]
> it's 4:35AM here in Taipei.

😱

**Comment by bluefoxlee** [comment]
>Hey, I've made quite a lot of changes to dev and then updated all the TFT files. If you have a chance, could you please give it a try and let me know if everything still ok?

I actually install new dev every time when I see you have an update for testing and daily use. XD 
I do have a little struggle on tft data error for past few days. Switch between main/dev and arduino/esp-idf to skip issue.

> I'm thinking about this. I can include all the files on the release, but remove this from the announcements.

Sounds good idea as we have not heard much feedback from Ja/Ko.

I uploaded the same tft (download from Dev), but can't reproduce percy10442's missing character issue. I will PR the new updated font today before it hit beta.

**Comment by edwardtfn** [comment]
> I uploaded the same tft (download from Dev), but can't reproduce percy10442's missing character issue. I will PR the new updated font today before it hit beta.

Still time. 😉 
I will sleep now and try to fix the last bugs tomorrow, then publish it to `beta` when all the other issues from this milestone are closed: https://github.com/Blackymas/NSPanel_HA_Blueprint/milestone/2

**Comment by edwardtfn** [comment]
All files are updated.
Could you please give it a try and let me know the results?

**Comment by bluefoxlee** [comment]
Work fine on my testing. hope it's working fine for Percy10442 then.

**Comment by percy10442** [comment]
I have a question, how do I update from beta?

**Comment by edwardtfn** [comment]
We are not on `beta` yet, so if you wanna try now, you should look at `dev`.
In your panel's yaml in ESPHome Dashboard, look for the `remote_packages` area and change from `ref: main` to `ref: beta` or `ref: dev`.
For the other files, you will have to download it manually from the `dev` branch from GitHub and update to your system: https://github.com/Blackymas/NSPanel_HA_Blueprint/tree/dev

**Comment by edwardtfn** [comment]
This might be useful: https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/784#discussioncomment-5809880

**Comment by percy10442** [comment]
I tried to update esphome but got an error, what am I missing?
<img width="1751" alt="截圖 2024-01-06 下午5 27 28" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/78840128/6097d2c9-7f7b-4538-bf50-71c5e729ee04">
<img width="1007" alt="截圖 2024-01-06 下午5 27 02" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/78840128/c4d6d860-757f-40d0-9461-abb3267b1a73">

**Comment by edwardtfn** [comment]
Try cleaning your build files. On the ESPHome Dashboard, find your device and click in the 3-dot menu related to your device and select "Clean build files".
Then try to install it again.

**Comment by percy10442** [comment]
I copied npanel_us_land.tft in dev, but there was still a problem. However, when I replaced it with npanel_CJK_us_land.tft, the result showed that it was normal. Edwardtfn , thank you for your help~

**Comment by edwardtfn** [comment]
- #1556

**Comment by bluefoxlee** [comment]
> Hello @bluefoxlee , as I know that the HKSCS extension doesn't consume too much space, it would be perfect for HKers if we include it.

@shing6326 forget to mention, the new CJK version of tft already include 548 HKSCS characters. not sure if its good enough for daily use.

**Comment by edwardtfn** [comment]
So, I'm planning to release this later today or tomorrow and this feature will be listed as "experimental".

Let's see what people says and we can work on that feedback.

Thanks a lot for your support!!

**Comment by shing6326** [comment]
> > Hello @bluefoxlee , as I know that the HKSCS extension doesn't consume too much space, it would be perfect for HKers if we include it.
> 
> @shing6326 forget to mention, the new CJK version of tft already include 548 HKSCS characters. not sure if its good enough for daily use.

Hello @bluefoxlee , really appreciate your efforts for the Chinese support. Those characters are already covered in my use. Let’s see if there are any HKers leaving their opinions here.

**Comment by bluefoxlee** [comment]
> So, I'm planning to release this later today or tomorrow and this feature will be listed as "experimental".
> Let's see what people says and we can work on that feedback.
> Thanks a lot for your support!!

Thank you for the great project and super support. It's the key reason I bought NSpanel for family use. 
unfortunately I still can't get PayPal done. 

Finger crossed for CJK. :P

**Comment by edwardtfn** [comment]
v4.2 was released

**Comment by edwardtfn** [comment]
We have just opened a discussion on #2332 about adding Thai chars. Your contribution will.be more than welcome. 😉
