### ISSUE TITLE
HW button indication fails when waking up

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1495]
> > @edwardtfn is there a way to delay turning on the display for 10ms after clicking? Sometimes the nspanel doesn't recognize the light is on straight away (so the bar stays white instead of light blue).
> 
> Looks like you found a bug. Which version are you running?

Version 4.1.4
I flashed the device 2 days ago and this is my first nspanel, so I've got everything to the (current) latest version.

The bug only happens when you are turning the screen on at the moment the light goes on, with this code:
```yaml
binary_sensor:
  - id: !extend left_button
    on_click:
      - lambda: |-
          if (current_page->state == "screensaver") disp1->goto_page("home");
  - id: !extend right_button
    on_click:
      - lambda: |-
          if (current_page->state == "screensaver") disp1->goto_page("home");
```

50% chance that the stripe above the button will go to lightblue, if not it takes some time until it recognizes it.

_Originally posted by @Xitro01 in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1281#issuecomment-1872809357_

**Comment by edwardtfn** [comment]
I believe this was already fixed by https://github.com/Blackymas/NSPanel_HA_Blueprint/commit/f251935ec6453101ec4a250bb64889da2fc51d84 which is still in `dev` and will be included in the next release.

**Comment by Xitro01** [comment]
Hi Edward. First of all the best wishes for 2024.
You picked this up really fast, looking forward for the release and will check if it’s fixed.

Any idea about a release date?

**Comment by edwardtfn** [comment]
It will depend on the testing results. I wanna release it before the end of this week.

**Comment by Xitro01** [comment]
> It will depend on the testing results. I wanna release it before the end of this week.

Awesome, will keep a close look on updates.

**Comment by Xitro01** [comment]
Hi @edwardtfn just flashed to [v4.2.1](https://github.com/Blackymas/NSPanel_HA_Blueprint/releases/tag/v4.2.1)
But this problem was not solved, the line above the button stays grey when my screen wakes while pressing the button.

**Comment by edwardtfn** [comment]
Is the button assigned to any entity via Blueprint?

**Comment by Xitro01** [comment]
> Is the button assigned to any entity via Blueprint?

Yes it is!
![Schermafbeelding 2024-01-15 150439](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/19844787/04ac720e-5d12-4f04-b70b-5069049268dc)

**Comment by edwardtfn** [comment]
I will need more details from your side, as this is working fine with me.
Can you see any error in Home Assistant logs (Settings > System > Logs)?

**Comment by edwardtfn** [comment]
Well, I kind of could duplicate the issue, but it was not exactly the same result.
I've used an automation to trigger the page Home and the light to turn-on at the same time, so I could see the page showing gray while the light was on, however after a couple of seconds it got updated.

I will investigate a bit more.

**Comment by edwardtfn** [comment]
I've applied a change to the TFT so it don't ask for the content of a page before the page is constructed. I'm afraid it could be the case before that your blueprint was sending the state update before the page was finished constructing.
This is still in `dev` and will be part of v4.2.3. Hopefully this improves the button indication to you.
I will close this for now and we can reopen if you still finding issues with the new version.

**Comment by Xitro01** [comment]
> I've applied a change to the TFT so it don't ask for the content of a page before the page is constructed. I'm afraid it could be the case before that your blueprint was sending the state update before the page was finished constructing. This is still in `dev` and will be part of v4.2.3. Hopefully this improves the button indication to you. I will close this for now and we can reopen if you still finding issues with the new version.

Sounds good, will test it after the next release!

**Comment by edwardtfn** [comment]
v4.2.3 was released.
Please let me know if that was fixed, otherwise we can reopen this.

**Comment by Xitro01** [comment]
Running 4.2.4 and that seems to have solved it. Worked without problems 5 out of 5 times, so assuming it is solved now. Thanks alot!
