### ISSUE TITLE
Buttonpage 2 shows no devices

### ISSUE THREAD

**Issue by smartmatic** [Blackymas/NSPanel_HA_Blueprint#246]
Hi,

first of all thank you for this amazing blueprint! I got  my first NS Panel and the configuration is really nice with your the help of this blueprint.

Unfortunately i am getting an error. Here is the full log

Logger: homeassistant.components.automation.bad_nspanel_configuration
Source: components/esphome/__init__.py:467 
Integration: Automation (documentation, issues) 
First occurred: 19:42:02 (6 occurrences) 
Last logged: 19:42:02

Bad: NSPanel Configuration: Choose at step 2: choice 27: Error executing script. Unexpected error for call_service at pos 2: Connection not done for nspanelbad @ 192.168.178.24; current state is ConnectionState.INITIALIZED!
Bad: NSPanel Configuration: Choose at step 2: choice 28: Error executing script. Unexpected error for call_service at pos 2: Connection not done for nspanelbad @ 192.168.178.24; current state is ConnectionState.INITIALIZED!
Bad: NSPanel Configuration: Error executing script. Unexpected error for choose at pos 2: Connection not done for nspanelbad @ 192.168.178.24; current state is ConnectionState.INITIALIZED!
While executing automation automation.bad_nspanel_configuration
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 467, in execute_service
    await entry_data.client.execute_service(service, call.data)
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 1083, in execute_service
    self._check_authenticated()
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 281, in _check_authenticated
    self._check_connected()
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 275, in _check_connected
    raise APIConnectionError(
aioesphomeapi.core.APIConnectionError: Connection not done for nspanelbad @ 192.168.178.24; current state is ConnectionState.INITIALIZED!
 
The panel is working and i have configured the start page with some sensors as well a thermostat page and the first button page.But the sensors linked to the second buttonpage are not displayed.

Waht can cause this issue?

**Comment by Blackymas** [comment]
hi - can you send blueprint yaml and esphome code

**Comment by deejaybeam** [comment]
This happens e.g. while rebooting nspanel or uploading tft - then the device can not be reached from homeassistant via api.
Or maybe a bad network - connection.

**Comment by smartmatic** [comment]
Ok, but there are several error in the log also this morning and i did not restart the panel

Error 1
`Logger: homeassistant.components.automation.bad_nspanel_configuration
Source: components/automation/__init__.py:567
Integration: Automation (documentation, issues)
First occurred: 08:07:13 (2 occurrences)
Last logged: 08:07:16

Error while executing automation automation.bad_nspanel_configuration: expected int for dictionary value @ data['message']`

Error 2
Logger: homeassistant.components.automation.bad_nspanel_configuration
Source: helpers/script.py:409
Integration: Automation (documentation, issues)
First occurred: 08:07:13 (4 occurrences)
Last logged: 08:07:16

Bad: NSPanel Configuration: Choose at step 2: choice 7: Error executing script. Invalid data for call_service at pos 4: expected int for dictionary value @ data['message']
Bad: NSPanel Configuration: Error executing script. Invalid data for choose at pos 2: expected int for dictionary value @ data['message']

**Comment by smartmatic** [comment]
> hi - can you send blueprint yaml and esphome code

ESPHome config
`substitutions:

###### CHANGE ME START ######

  device_name: "nspanelbad" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://my-ip/:8123/local/nspanel.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft" # URL to Github

##### CHANGE ME END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####`

Blueprint yaml

`alias: "Bad: NSPanel Configuration"
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: nspanelbad
    language: DEU
    weather_entity: weather.smart_live
    outdoortemp: sensor.vicare_outside_temperature
    indoortemp: sensor.bad_wt_actual_temperature
    humidity: sensor.bad_wt_actual_humidity
    hotwatertemp: sensor.vicare_supply_temperature
    left_button_entity: light.dusche
    right_button_entity: light.bad
    heatingsystemflame: binary_sensor.vicare_burner_active
    climate: climate.bad_wt
    entity01: light.dusche
    entity01_name: Group
    entity02: light.hue_color_spot_1_4
    button_page01_label: Bad Lichter
    entity01_confirm: false
    entity05_name: Group
    entity09: cover.bad
    entity09_name: Rolladen
    entity10: scene.badezimmer_miami
    entity10_name: Miami
    entity11: scene.badezimmer_nordlichter
    entity11_name: Nordlichter
    button_page02_label: Andere Sensoren
    right_button_name: Waschbecken
    left_button_name: Dusche
    entity02_name: Dusche1
    entity03: light.hue_color_spot_1_5
    entity03_name: Dusche2
    entity04: light.hue_color_spot_1_6
    entity04_name: Dusche3
    entity05: light.bad
    entity06: light.hue_color_spot_1
    entity06_name: Waschbecken1
    entity07: light.hue_color_spot_1_2
    entity07_name: Waschbecken2
    entity08: light.hue_color_spot_1_3
    entity08_name: Waschbecken3
`

**Comment by deejaybeam** [comment]
> Ok, but there are several errors in the log also this morning and i did not restart the panel
> 
> Error 1 `Logger: homeassistant.components.automation.bad_nspanel_configuration Source: components/automation/**init**.py:567 Integration: Automation (documentation, issues) First occurred: 08:07:13 (2 occurrences) Last logged: 08:07:16
> 
> Error while executing automation automation.bad_nspanel_configuration: expected int for dictionary value @ data['message']`
> 
> Error 2 Logger: homeassistant.components.automation.bad_nspanel_configuration Source: helpers/script.py:409 Integration: Automation (documentation, issues) First occurred: 08:07:13 (4 occurrences) Last logged: 08:07:16
> 
> Bad: NSPanel Configuration: Choose at step 2: choice 7: Error executing script. Invalid data for call_service at pos 4: expected int for dictionary value @ data['message'] Bad: NSPanel Configuration: Error executing script. Invalid data for choose at pos 2: expected int for dictionary value @ data['message']

This can safely be ignored and is already fixed in dev-branch.
Cause is, even if nothing is assigned to a "button-slot" the blueprint tries to execute a toggle for the (not assigned) entity.

**Comment by smartmatic** [comment]
I‘ve played a bit with the display and found out that the entities i missed on buttonpage 2 are there but not displayed. At least both scene entities are now visible after i touched the display on the place where the icons should be!

But you can see that entity09 (button09) is still not visible but i control the device when i hold the button and the menu opens for that device. 

![75390646-ECB0-4C8B-AA45-1541FD5C401C](https://user-images.githubusercontent.com/74932663/215113812-49792103-1ef9-4fb9-8140-b616037853ee.jpeg)

![DA5DF639-0017-42C2-A4C1-0B98A52DE2F1](https://user-images.githubusercontent.com/74932663/215113871-d83b51f3-ff59-4ba8-93bd-c537c8152d8a.jpeg)


So it looks like the nspanel.tft has an issue.

**Comment by danwright87** [comment]
Hi,
Can you try restarting the device, I have a feeling that will resolve it

**Comment by deejaybeam** [comment]
That´s correct - currently (v3.0.0) if you add entities to buttons, you have to restart the device to run the init-code of the blueprint. So you have to trigger the button to update the display. In dev-branch we already trigger the init on "automation-reload" to exec the init part.

**Comment by smartmatic** [comment]
> Hi, Can you try restarting the device, I have a feeling that will resolve it

No, restart, does not make the icon visible

**Comment by Blackymas** [comment]
Hallo,

also nochmal zur Klärung.

Bei eine Reboot wird während der boot page alle buttons nacheinander abgefragt und erstellt. Die erstellen buttons werden in einer Global datei gespeichert.


Wird also auf einer Seite etwas nicht angezeigt dann läuft die Abfrage der Buttons nicht durch.

Da ich das nicht reproduzieren kann und auch in den Videos von mark Watt und Smarthome Yourself die buttons da sind muss hier irgendwas bei dir nicht stimmen.


Das selbe gilt auch für deine Beschreibung "wenn ich auf die Fläche klicke, dann ist es da" hier wurde auch beim boot anscheinend aus Grund X die Buttons nicht alle geladen.

Durch das "drauf klicken" wir eine einzelnen automation ausgelöst, die dann den zustand vom Button ändert und danach wird der Button angezeigt.


Leg mal auf den Button irgendwas anderes drauf und am besten Entitys nicht doppelt vergeben.


Um überhaupt einen Einblick in diese Problem zu bekommen müssten wir auch unter Trace de boot Vorgang von dir bekommen.

Wie ich in discord erklärt hatte ist der Bootvorgang die erste Spalte. Wenn man oben den Zeitstempel ändert sollte man irgendwann die richtige Orange Linie finden.

Was anderes können wir aus der ferne weder sagen noch machen - auch wenn wir gerne würden

**Comment by Blackymas** [comment]
sollte sich ja mit 
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/255#issuecomment-1407331033

erledigt haben - sonst noch einmal melden
