### ISSUE TITLE
Panel works, but stays in the sceen "boot"

### ISSUE THREAD

**Issue by Timmo3** [Blackymas/NSPanel_HA_Blueprint#253]
Hi, 

great project!

But I got a small probelm: I got the panel "working" but it does not leave the blue boot screen with the HA logo.
The switches are working left and right, but the boot screen does not change after booting. 

Is this a known problem?

Best regards
Timmo

There is the nspanel.yaml

substitutions:

###### CHANGE ME START ######

  device_name: "nspanel" 
  wifi_ssid: "xxxxxx"
  wifi_password: "xxxxxxx"

  nextion_update_url: "http://172.16.0.70:8123/local/nspanel.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft" # URL to Github

##### DO NOT CHANGE ANYTHING! #####

packages:
[logs_nspanel_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10511884/logs_nspanel_logs.txt)

  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

**Comment by Timmo3** [comment]
...the service call 

```
service: esphome.nspanel_send_command_printf
data:
  cmd: page home
```

...does work so, I got it working. But after each reboot, the boot screen still keeps sticking.

**Comment by danwright87** [comment]
That means there is an issue with the blueprint , have you installed it and deployed it? Looks like your device name is nspanel so you will need to make sure it matches in the blueprint exactly.

**Comment by Timmo3** [comment]
Hi Dan, 

the blueprint is installed and deployed (entry in the automations, which is triggerd every minute). 
The code looks like this (the name "nspanel" seems to be correct)

id: '1674755989818'
alias: NSPanel Configuration
description: ''
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: nspanel
    language: DE
    outdoortemp: sensor.gw1100a_v2_2_0_outdoor_temperature
    humidity: sensor.gw1100a_v2_2_0_humidity
    left_button_entity: switch.shelly_eingang_licht
    left_button_name: Licht Flur
    right_button_entity: switch.shelly_wz_tisch_lampe_switch_0
    right_button_name: Wohnzimmertisch

**Comment by danwright87** [comment]
Hi, make sure you have deleted any old ESPHome integrations you may have had for the screen + the new one and re-add it, I've seen issues if it clashes

**Comment by Blackymas** [comment]
if the boot page does not disappear it is a problem in the boot process i.e. it is not completed.

and hangs somewhere

look here. If you restart the nspanel and then go directly to trace in the automation you can select a timestamp at the top.

The orange line must then go exactly to the first column.

https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#1-how-do-I-create-issues-when-I-have-a-problem

**Comment by hessedoggy** [comment]
Hey after updating ESP I have the same issue. 
in my bootlog I found the following error : [12:39:26][W][nextion:318]: Nextion reported invalid instruction! 
and the panel sticks in the bootlogo. the buttons works and in Homeassistent it shows everything okay.

**Comment by Rainerlan** [comment]
I have the same problem: The panel seem to work, only the boot-screen remains displayed all the time.
When disconnecting & reconnecting power, the "normal" homesreeen is visible for a fraction of a second. 
Afterwards its the boot screen again.
When I look at the trace as suggested, at all timestamps the trace looks ok. 
Find attached an example - sorry for the size, the trace is a huge one:)
<img width="849" alt="Screenshot 2023-01-31 010702" src="https://user-images.githubusercontent.com/179617/215624999-5ff4be5c-8d86-481f-ae47-8de6d49541f2.png">
In the example I have pressed the right physical key of the panel. This triggers the correct action: Switch the relay (by increasing the set-temp to 0.5deg over the current-temp and hence the generic thermostat device, connected to relay 1 toggles the relay).
<img width="688" alt="Screenshot 2023-01-31 011045_2" src="https://user-images.githubusercontent.com/179617/215625621-c0e52c98-ebe3-4a28-a44f-8c6f4ceaaa80.png">

What is the condition of the esphome on esp32 to command the display to transition from boot-screen to "home-screen"?
It seems as if some condition is not met - so that the command to switch from boots screen to home screen is not issued on HMI TX.

**Comment by trondtorsoe** [comment]
Hi

I had the same problem on my US panel. Got stuck at startup...

I made an automation that waited for the status of switch.<device>_nextion_inited  to be ON and then jumped to home page ( service: send_command_printf) when ready.
Not a proper solution - but it works for now.

![2023-01-31 20 15 39](https://user-images.githubusercontent.com/50380501/215861658-6528546f-3414-4efe-915f-cafdd8247cf4.png)
![2023-01-31 20 16 12](https://user-images.githubusercontent.com/50380501/215861679-186684c8-70bc-4275-bc5c-4e22bfecdbac.png)

**Comment by Rainerlan** [comment]
I also found an intermediate fix - unfortunately after a power-loss it has to be applied again :(

In HA, got "developertools" (ger. Entwicklungswerkzeuge) -> Events (ger.: Ereignisse) and select the Event "ESPHome: nspanel_wz_send_command_printf" and add as cmd "page screensaver"
![Screenshot 2023-01-31 202631_5](https://user-images.githubusercontent.com/179617/215862478-1fa30e33-08ee-415e-bfda-2b34016680ae.png)

**Comment by Blackymas** [comment]
hi guys this is all a bit confusing what you write here.

With a reboot nextion must be switched inited otherwise the boot does not start at all.

Now just jumping to a page via HA service is also not the best idea, because then probably the buttons etc will not be loaded.

If the buttons are there, the problem must be to look for it.

Have you deleted the blueprint and created a new one?

A problem with the blueprint is the issue when you delete something out again. Then it is not deleted correctly in the blueprint.

Look into the blueprint yaml if there is a field without value.
![Bildschirmfoto 2023-01-31 um 21 30 29](https://user-images.githubusercontent.com/41958506/215875869-1cf789c7-88c8-4b2b-b734-9fb1205bcb55.png)

**Comment by Blackymas** [comment]
ich schreib mal auf deutsch ;)

den Übergang zur Homepage wird im boot Vorgang als letzte ausgelöst. Wenn du kein "beep" hörst und danach zur homepage springst ist der boot Vorgang nicht durchgelaufen.

Kannst du mal das Blueprint löschen und ein neues erstellen und mal nur diese Felder uns sonst nichts ausfüllen
![Bildschirmfoto 2023-02-01 um 01 10 13](https://user-images.githubusercontent.com/41958506/215913031-136b8c26-271f-4d36-8040-3bfffd57c23e.png)


Dann können wir uns an das Problem ran arbeiten.

Die neueste Bleuprint version und esphome Version hast du drauf? gehe mal stark davon aus.

Weil ich das problem nicht nachstellen kann.

**Comment by Blackymas** [comment]
oder du wartest bist zum we da kommt wahrscheinlich 3.1.0 da haben wir das boot Menü etwas umgebaut.

Wie gesagt um das Problem wirklich zu finden müssten wir den Zeitstempel sehen wo die orange Linie den 1 zweig abarbeitet - denn da sieht man wo es hängen bleibt

**Comment by Rainerlan** [comment]
Interessant...Ich habs probiert - und dachte schon er funktioniert nicht.
Nach einem Power-cycle hat es nach ca. 20s 2x kurz gepiept und der Inhalt wurde korrekt angezeigt.
Ich bin gespannt ob das Problem mal wieder auftaucht - und ob das selbe Vorgehen dann erneut funktioniert.
Viele Dank für Deinen Support!

**Comment by benek984** [comment]
I have the same problem but non of your suggestions works as fix.  After flashing and uploading .tft I only can see HA logo on the display. Physical button function works with blueprint. In the ESPHOME logs I can see below entries:
````
[19:19:25][E][uart:015]: Reading from UART timed out at byte 0!
[19:19:25][W][nextion:078]: Nextion is not connected! 
[19:19:26][E][uart:015]: Reading from UART timed out at byte 0!
[19:19:26][W][nextion:078]: Nextion is not connected! 
[19:19:26][E][uart:015]: Reading from UART timed out at byte 0!
[19:19:26][W][nextion:078]: Nextion is not connected! 
[19:19:27][E][uart:015]: Reading from UART timed out at byte 0!
[19:19:27][W][nextion:078]: Nextion is not connected! 
````

When trying to upload tft again i get this 
````
[19:21:01][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:01][W][nextion:078]: Nextion is not connected! 
[19:21:02][D][switch:013]: 'nspanel01 Update TFT display' Turning ON.
[19:21:02][D][nextion_upload:169]: Connected
[19:21:02][D][nextion_upload:175]: Requesting URL: https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft
[19:21:03][D][nextion_upload:209]: Updating Nextion ...
[19:21:03][D][nextion_upload:235]: Waiting for upgrade response
[19:21:03][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:03][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:03][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:03][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:03][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:03][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:04][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:04][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:04][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:04][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:04][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:04][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:04][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:04][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:04][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:05][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:05][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:05][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:05][E][uart:015]: Reading from UART timed out at byte 0!
[19:21:05][D][nextion_upload:239]: Upgrade response is  19
[19:21:05][D][nextion_upload:242]: Available 0 : 0x00
[19:21:05][D][nextion_upload:242]: Available 1 : 0x00
[19:21:05][D][nextion_upload:242]: Available 2 : 0x00
[19:21:05][D][nextion_upload:242]: Available 3 : 0x00
[19:21:05][D][nextion_upload:242]: Available 4 : 0x00
[19:21:05][D][nextion_upload:242]: Available 5 : 0x00
[19:21:05][D][nextion_upload:242]: Available 6 : 0x00
[19:21:05][D][nextion_upload:242]: Available 7 : 0x00
[19:21:05][D][nextion_upload:242]: Available 8 : 0x00
[19:21:05][D][nextion_upload:242]: Available 9 : 0x00
[19:21:05][D][nextion_upload:242]: Available 10 : 0x00
[19:21:05][D][nextion_upload:242]: Available 11 : 0x00
[19:21:05][D][nextion_upload:242]: Available 12 : 0x00
[19:21:05][D][nextion_upload:242]: Available 13 : 0x00
[19:21:05][D][nextion_upload:242]: Available 14 : 0x00
[19:21:05][D][nextion_upload:242]: Available 15 : 0x00
[19:21:05][D][nextion_upload:242]: Available 16 : 0x00
[19:21:05][D][nextion_upload:242]: Available 17 : 0x00
[19:21:05][D][nextion_upload:242]: Available 18 : 0x00
[19:21:05][D][nextion_upload:248]: preparation for tft update failed 0 ""
[19:21:05][D][nextion_upload:324]: Restarting Nextion
INFO nspanel01.local: Error while reading incoming messages: Error while reading data: [Errno 104] Connection reset by peer
INFO nspanel01.local: Ping Failed: Error while reading data: [Errno 104] Connection reset by peer
INFO Disconnected from ESPHome API for nspanel01.local
WARNING Disconnected from API
INFO Successfully connected to nspanel01.local
[19:21:16][C][ntc:014]: NTC Sensor 'nspanel01 Temperature'

````
PLEASE HELP

**Comment by Blackymas** [comment]
use local path

**Comment by benek984** [comment]
still the same:

````
19:40:33][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:33][W][nextion:078]: Nextion is not connected! 
[19:40:33][D][switch:013]: 'nspanel01 Update TFT display' Turning ON.
[19:40:33][D][nextion_upload:169]: Connected
[19:40:33][D][nextion_upload:175]: Requesting URL: https://192.168.10.21:8123/local/nspanel.tft
[19:40:34][D][nextion_upload:209]: Updating Nextion ...
[19:40:34][D][nextion_upload:235]: Waiting for upgrade response
[19:40:34][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:34][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:34][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:35][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:35][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:35][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:35][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:35][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:35][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:35][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:35][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:35][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:36][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:36][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:36][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:36][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:36][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:36][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:36][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:36][D][nextion_upload:239]: Upgrade response is  19
[19:40:36][D][nextion_upload:242]: Available 0 : 0x00
[19:40:36][D][nextion_upload:242]: Available 1 : 0x00
[19:40:36][D][nextion_upload:242]: Available 2 : 0x00
[19:40:36][D][nextion_upload:242]: Available 3 : 0x00
[19:40:36][D][nextion_upload:242]: Available 4 : 0x00
[19:40:36][D][nextion_upload:242]: Available 5 : 0x00
[19:40:36][D][nextion_upload:242]: Available 6 : 0x00
[19:40:36][D][nextion_upload:242]: Available 7 : 0x00
[19:40:36][D][nextion_upload:242]: Available 8 : 0x00
[19:40:36][D][nextion_upload:242]: Available 9 : 0x00
[19:40:36][D][nextion_upload:242]: Available 10 : 0x00
[19:40:36][D][nextion_upload:242]: Available 11 : 0x00
[19:40:36][D][nextion_upload:242]: Available 12 : 0x00
[19:40:36][D][nextion_upload:242]: Available 13 : 0x00
[19:40:36][D][nextion_upload:242]: Available 14 : 0x00
[19:40:36][D][nextion_upload:242]: Available 15 : 0x00
[19:40:36][D][nextion_upload:242]: Available 16 : 0x00
[19:40:36][D][nextion_upload:242]: Available 17 : 0x00
[19:40:36][D][nextion_upload:242]: Available 18 : 0x00
[19:40:36][D][nextion_upload:248]: preparation for tft update failed 0 ""
[19:40:36][D][nextion_upload:324]: Restarting Nextion
[19:40:38][D][nextion_upload:327]: Restarting esphome
INFO nspanel01.local: Error while reading incoming messages: Error while reading data: [Errno 104] Connection reset by peer
INFO nspanel01.local: Ping Failed: Error while reading data: [Errno 104] Connection reset by peer
INFO Disconnected from ESPHome API for nspanel01.local
WARNING Disconnected from API
INFO Successfully connected to nspanel01.local
[19:40:49][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:49][W][nextion:078]: Nextion is not connected! 
[19:40:49][E][uart:015]: Reading from UART timed out at byte 0!

````

**Comment by benek984** [comment]
Even tried my spare HA that is accessible on http instead of https and the same:

````
[19:44:13][W][nextion:078]: Nextion is not connected! 
[19:44:13][D][api:102]: Accepted ::FFFF:192.168.10.21
[19:44:13][D][api.connection:918]: Home Assistant 2023.2.0 (::FFFF:192.168.10.21): Connected successfully
[19:44:13][D][switch:013]: 'nspanel01 Update TFT display' Turning ON.
[19:44:13][D][nextion_upload:169]: Connected
[19:44:13][D][nextion_upload:175]: Requesting URL: http://192.168.10.23:8123/local/nspanel.tft
[19:44:13][D][nextion_upload:209]: Updating Nextion ...
[19:44:13][D][nextion_upload:235]: Waiting for upgrade response
[19:44:13][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:13][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:14][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:14][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:14][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:14][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:14][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:14][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:14][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:14][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:14][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:14][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:15][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:15][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:15][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:15][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:15][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:15][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:15][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:15][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:15][D][nextion_upload:239]: Upgrade response is  20
[19:44:15][D][nextion_upload:242]: Available 0 : 0x00
[19:44:15][D][nextion_upload:242]: Available 1 : 0x00
[19:44:15][D][nextion_upload:242]: Available 2 : 0x00
[19:44:15][D][nextion_upload:242]: Available 3 : 0x00
[19:44:15][D][nextion_upload:242]: Available 4 : 0x00
[19:44:15][D][nextion_upload:242]: Available 5 : 0x00
[19:44:15][D][nextion_upload:242]: Available 6 : 0x00
[19:44:15][D][nextion_upload:242]: Available 7 : 0x00
[19:44:15][D][nextion_upload:242]: Available 8 : 0x00
[19:44:15][D][nextion_upload:242]: Available 9 : 0x00
[19:44:15][D][nextion_upload:242]: Available 10 : 0x00
[19:44:15][D][nextion_upload:242]: Available 11 : 0x00
[19:44:15][D][nextion_upload:242]: Available 12 : 0x00
[19:44:15][D][nextion_upload:242]: Available 13 : 0x00
[19:44:15][D][nextion_upload:242]: Available 14 : 0x00
[19:44:15][D][nextion_upload:242]: Available 15 : 0x00
[19:44:15][D][nextion_upload:242]: Available 16 : 0x00
[19:44:15][D][nextion_upload:242]: Available 17 : 0x00
[19:44:15][D][nextion_upload:242]: Available 18 : 0x00
[19:44:15][D][nextion_upload:242]: Available 19 : 0x00
[19:44:15][D][nextion_upload:248]: preparation for tft update failed 0 ""
[19:44:15][D][nextion_upload:324]: Restarting Nextion
INFO nspanel01.local: Error while reading incoming messages: Error while reading data: [Errno 104] Connection reset by peer
INFO nspanel01.local: Ping Failed: Error while reading data: [Errno 104] Connection reset by peer
INFO Disconnected from ESPHome API for nspanel01.local
WARNING Disconnected from API
INFO Successfully connected to nspanel01.local
[19:44:29][E][uart:015]: Reading from UART timed out at byte 0!
[19:44:29][W][nextion:078]: Nextion is not connected! 
[19:44:29][E][uart:015]: Reading from UART timed out at byte 0!


````

**Comment by Blackymas** [comment]
Please take a look at the link below. These are all topics related to your problem. Check under "closed" - the issue can definitely be resolved if you use the blank file or upload it with Tasmota.

It seems like the incorrect baud rate is fixed for you, so the upload is not working


https://github.com/Blackymas/NSPanel_HA_Blueprint/issues?q=is%3Aissue+is%3Aopen+Nextion+is+not+connected%21+

**Comment by X-Ryl669** [comment]
This is what I did to fix the issue (I thought I had broken something in my local change, but it seems it's in the official release too):

Look into your nspanel.yaml in ESPHome in the bottom of the file:
```
##### START - DISPLAY START CONFIGURATION #####
display:
  - platform: nextion
    id: disp1
    uart_id: tf_uart
    tft_url: ${nextion_update_url}
    on_setup:
      then:
        - lambda: id(disp1).send_command_printf("page 8");
        - wait_until:
            api.connected
        - delay: 0.5s
        - number.set:
            id: display_brightness
            value: !lambda 'return id(display_brightness_global);'
        - number.set:
            id: display_dim_brightness
            value: !lambda 'return id(display_dim_brightness_global);'
        - lambda: id(disp1).set_component_text_printf("settings.a03", "%i", id(display_brightness_global));
        - lambda: id(disp1).set_component_text_printf("settings.a04", "%i", id(display_dim_brightness_global));
        - lambda: id(disp1).send_command_printf("settings.brightslider.val=%i", id(display_brightness_global));
        - lambda: id(disp1).send_command_printf("settings.dimslider.val=%i", id(display_dim_brightness_global));
        - lambda: id(disp1).send_command_printf("home.sleepmodus.val=%i", id(sleep_modus_global));
        - lambda: id(disp1).set_component_value("settings.a02", id(sleep_modus_global) == 1);
        - delay: 0.5s
        - lambda: id(disp1).send_command_printf("page home");
        - switch.template.publish:
            id: nextion_init
            state: on
```
I've added the line `- lambda: id(disp1).send_command_printf("page home");` just before the `nextion_init` event is published so it fallback to home screen upon initialization by itself and does not depends on HA's automation here. It doesn't cause any trouble, since if HA change the page to home, it's already done. Everything else is working perfectly.

**Comment by deejaybeam** [comment]
We have removed the "page home" from esphome, because of some changes in the boot sequence.
This is also in 3.1.0. We want to jump to home directly after the init-section is finished. The duration of this depends on how many buttons are assinged, the setting of the delay and what queries are required. It was also important for us to ensure that the init has finished successfully. ONLY if HA calls "page home" (which triggers some other queries) everything was done as it should. If this not happens, then there must be something wrong with the configuration - missing entity, faulty automation, ... and THIS has to be fixed.

**Comment by X-Ryl669** [comment]
Well, I guess I'll need to wait until 3.1.0 is released to update my scripts. 

Right now, the automation doesn't clearly get the panel out of boot for me and the **huge** alternative paths is just too big to debug for me. Since everything is working even if the automation isn't sending the page home command, I guess it's not too hard to have a fallback. 

Maybe the nextion_init event happens while the automation is already processing something else, but clearly, it doesn't send the page home command.

**Comment by benek984** [comment]
> Please take a look at the link below. These are all topics related to your problem. Check under "closed" - the issue can definitely be resolved if you use the blank file or upload it with Tasmota.
> 
> It seems like the incorrect baud rate is fixed for you, so the upload is not working
> 
> https://github.com/Blackymas/NSPanel_HA_Blueprint/issues?q=is%3Aissue+is%3Aopen+Nextion+is+not+connected%21+

So I tasmotised my nspanel and trying to flash empty tft but still no luck. 
I starting to believe that I damaged my nspanel some how.

````
19:07:18.554 CMD: FlashNextion http://192.168.10.23:8123/local/nspanel_blank.tft
19:07:18.555 SRC: WebConsole from 192.168.10.50
19:07:18.558 CMD: Grp 0, Cmd 'FLASHNEXTION', Idx 1, Len 49, Pld -99, Data 'http://192.168.10.23:8123/local/nspanel_blank.tft'
19:07:18.575 RSL: RESULT = {"FlashNextion":"Done"}
19:07:18.602 FLH: host: 192.168.10.23, port: 8123, get: /local/nspanel_blank.tft
19:07:18.606 WIF: DNS resolved '192.168.10.23' (192.168.10.23) in 0 ms
19:07:18.631 FLH: Connected:true
19:07:18.737 FLH: Retry 2
19:07:19.059 FLH: HTTP Respose is 200 OK or 206 Partial Content
19:07:19.062 FLH: Flash file size: 263492
19:07:19.066 NXP: Nextion command sent = bytes('4452414B4A485355594447424E434A48474A4B534842444EFFFFFF')
19:07:19.079 NXP: Nextion command sent = bytes('7265636D6F643D30FFFFFF')
19:07:19.082 NXP: Nextion command sent = bytes('7265636D6F643D30FFFFFF')
19:07:19.085 NXP: Nextion command sent = bytes('636F6E6E656374FFFFFF')
````

**Comment by Blackymas** [comment]
look at the issues times there are some posts about it.

in the release notes 3.1.0 I have also linked some contributions

**Comment by benek984** [comment]
@Blackymas would you be able to add possibility to set badu rate rather fixing it at 115200? The issue I come across turns out to be a problem with badu rate. For some reason my NSPanel has to be set to 9600 instead of 115200. It would be helpful to be able to change the badu rate in ChangME section.
