### ISSUE TITLE
v4.3.33 still not working for me boot loop/encryption key changed

### ISSUE THREAD

**Issue by BaltasarParreira** [Blackymas/NSPanel_HA_Blueprint#2873]
### TFT Version

v4.3.33

### Firmware Version

v4.3.33

### Blueprint Version

v4.3.33

### Panel Model

EU

### What is the bug?

Boot loop and after encryption changed

### Your Panel's YAML

```
api:
  encryption:
    key: "xxxxxxxxxx"
    
substitutions:
  # Settings - Editable values
  device_name: "mynspanel"
  friendly_name: "MyNSPanel"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  #nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"
  #DELAY_DEFAULT: 250  # Only for ref: dev

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package

```

### ESPHome Logs

```INFO Upload took 10.37 seconds, waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from 192.168.0.44 using esphome API
INFO Successfully resolved mynspanel @ 192.168.0.44 in 0.000s
WARNING Can't connect to ESPHome API for mynspanel @ 192.168.0.44: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.0.44', port=6053))]: [Errno 113] Connect call failed ('192.168.0.44', 6053) (SocketAPIError)
INFO Trying to connect to mynspanel @ 192.168.0.44 in the background
INFO Successfully resolved mynspanel @ 192.168.0.44 in 0.000s
INFO Successfully resolved mynspanel @ 192.168.0.44 in 0.000s
INFO Successfully resolved mynspanel @ 192.168.0.44 in 0.000s
INFO Successfully connected to mynspanel @ 192.168.0.44 in 0.102s
INFO Successfully resolved mynspanel @ 192.168.0.44 in 0.000s
INFO Successfully connected to mynspanel @ 192.168.0.44 in 0.084s
INFO Successfully resolved mynspanel @ 192.168.0.44 in 0.000s
INFO Successfully connected to mynspanel @ 192.168.0.44 in 0.081s

```

### Home Assistant Logs

```text

```

Hi, still not working for me this latest version.
After installed it stayed again with a screen loop and log as show repting the last lines forever.
Also Home assistant keeps saying that the key changed showing this to resolve:

<img width="746" height="535" alt="Image" src="https://github.com/user-attachments/assets/c43dfa40-8a03-4796-96c4-884f1a4bf1d2" />

But even puting again the same key I have on the YAML file keeps giving the same error.
I remove the esphome device, reboot HA, it detect again but with same key problem and couldn't solve this.

Went back again to the v4.3.19 with ESPHome 2025.7.5 and all ok and normal again.

**Comment by edwardtfn** [comment]
The yaml you shared is broken. Could you please double check?

Also, could you please add this and flash it again. It should wipe the device memory (NVS) which could be causing the crash on boot.
```yaml
factory_reset:
  resets_required: 5
  max_delay: 45s
```

**Comment by BaltasarParreira** [comment]
> The yaml you shared is broken. Could you please double check?
> 
> Also, could you please add this and flash it again. It should wipe the device memory (NVS) which could be causing the crash on boot.
> 
> factory_reset:
>   resets_required: 5
>   max_delay: 45s

Broken in what way?
That's all the code I have on v4.3.19 that works.

**Comment by shaggee** [comment]
Had same issue. I fixed it by flashing firmware couple times. Some of the panela requires 5-time flashing to make it work.

**Comment by edwardtfn** [comment]
> > The yaml you shared is broken. Could you please double check?
> > Also, could you please add this and flash it again. It should wipe the device memory (NVS) which could be causing the crash on boot.
> > factory_reset:
> > resets_required: 5
> > max_delay: 45s
> 
> Broken in what way? That's all the code I have on v4.3.19 that works.

It is missing at least one line at the top. It is starting with and indented `encryption`.

**Comment by edwardtfn** [comment]
Anyhow, for the encryption issue you could remove your panel's integration from Settings > Devices and Services > ESPHome and add it again. It will request the key again and it should work.

**Comment by BaltasarParreira** [comment]
> Anyhow, for the encryption issue you could remove your panel's integration from Settings > Devices and Services > ESPHome and add it again. It will request the key again and it should work.

Yes regarding the YAML, the "api" part of the YAML code was there but was after the <> code character so GitHub was not showing it, did an enter and now show it.

For the key I did what you said since first I search around the net for solutions for that, but after I add it again it asks for the key again and doesn't solve it.

Going try now the various uploads to see what resolves or not.

**Comment by BaltasarParreira** [comment]
Greatttttt !!!!
With the lines you said to add is working and the key problem disappeared.
Thank you !!!

Is this version also working with Bluetooth proxy as it says on the release "Bluetooth compatibility - enable stable operation with Bluetooth add-ons" ?

Can I add this to my YAML?
```
bluetooth_proxy:
  active: true
  connection_slots: 3
```

**Comment by edwardtfn** [comment]
No, it isn't working with Bluetooth yet.
I'm working on this. 😉
