### ISSUE TITLE
AttributeError: 'list' object has no attribute 'lower'

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#318]
Everything looks do be working fine, but I'm having those entries on Home Assistant log (for both panels I have):
```txt
Logger: homeassistant.components.automation.office_workstation_panel_configuration
Source: helpers/script.py:409
Integration: Automation (documentation, issues)
First occurred: 10:56:54 (3 occurrences)
Last logged: 10:56:54

Office - Workstation - Panel - Configuration: Choose at step 2: choice 26: Choose at step 1: choice 1: Error executing script. Error rendering template for variables at pos 13: AttributeError: 'list' object has no attribute 'lower'
Office - Workstation - Panel - Configuration: Choose at step 2: choice 26: Error executing script. Error rendering template for choose at pos 1: AttributeError: 'list' object has no attribute 'lower'
Office - Workstation - Panel - Configuration: Error executing script. Error rendering template for choose at pos 2: AttributeError: 'list' object has no attribute 'lower'
```

I've just updated my panel (ESPHome) and blueprint to the latest version available 5 min ago.

**Comment by nitruxa** [comment]
@edwardtfn try adding "Hot Water Temperature Sensor (Optional)" and see if that error goes away.
I had same issue yesterday, and while tracing I've noticed that it comes from certain templates related to hot water sensor entity. After adding the enity - errors are not showing up 🤔

**Comment by edwardtfn** [comment]
Unfortunately I still having the same issue after adding a sensor for `hotwatertemp`.

```txt
Logger: homeassistant.components.automation.hall_panel_configuration
Source: components/automation/__init__.py:567 
Integration: Automation (documentation, issues) 
First occurred: 16:04:13 (1 occurrences) 
Last logged: 16:04:13

Error while executing automation automation.hall_panel_configuration: AttributeError: 'list' object has no attribute 'lower'
```

**Comment by nitruxa** [comment]
try to trace the automation, it will help you to find exact block which is failing.

**Comment by edwardtfn** [comment]
It's a bit hard to catch this with a trace as the automation is triggered many times per minute while the error happens once or twice per hour, so when I find a new occurrence in the log it is already to late to find that in the trace...
I will keep trying.

**Comment by edwardtfn** [comment]
I got it.

It is happening when triggered by a new page being selected (home page), then after a million actions it crashed at a variable calculation related to the weather:

![1A61C5D6-8D45-4B63-9717-1DC71D6BA3AF](https://user-images.githubusercontent.com/94725493/218161100-95134732-2e38-419f-a156-2011da14f7ad.png)
![12C6C7E5-3807-4F80-81FA-C107C14568EA](https://user-images.githubusercontent.com/94725493/218161114-302ac2e0-690a-4278-9317-a84d2640402e.jpeg)

**Comment by deejaybeam** [comment]
looks interesting, but I don´t see really what´s going wrong here.
The weather source is Accuweather.
The weather entity is "weather.home".
The current state is "rainy".
So the variable "weather_pic" could be created.

I know, in older versions there was a but that tries to access unassigned entities (like the hotwater) but this should all be fixed in the meanwhile.
I have a dev-env and without assigning anything else than the nspanel name.
Only thing im missing in your automation-config is: "language" - have you set it?

**Comment by edwardtfn** [comment]
> Only thing im missing in your automation-config is: "language" - have you set it?

I've set language (ENG) after your question, but still the same issue. :(

**Comment by edwardtfn** [comment]
> accuweather: home

I believe the problem was with the weather settings, as I haven't changed when updating to the new blueprint version. After setting the weather entity properly with the new blueprint I couldn't see this error message anymore.

The new settings are like this:
```txt
weather_entity: weather.home
```

So I'm closing this and will open again if I see this error message again in the future.
